language: android
dist: trusty
android:
  components:
    - build-tools-28
    - android-28
    - add-on
    - extra
  before_install:
  - yes | sdkmanager "platforms;android-28"
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

# Run assemble and unit tests
script:
  - ./gradlew clean assembleDebug assembleRelease testDebug
